/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplicacao;

import modelo.Categoria;
import java.sql.Connection;
/**
 *
 * @author Y
 */

public class frmLobby extends javax.swing.JFrame {

    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmLobby.class.getName());
    
    /**
     * Creates new form frmLobby
     */
    public frmLobby() {
        initComponents();
        
        }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new CustomPanel("/recurso/nossa_imagem.jpg");
        btnArmario = new javax.swing.JButton();
        btnGeladeira = new javax.swing.JButton();
        btnBd = new javax.swing.JButton();
        jlChoose = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NOSSA Despensa");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/recurso/icone.png")).getImage());

        btnArmario.setText("Armário");
        btnArmario.addActionListener(this::btnArmarioActionPerformed);

        btnGeladeira.setText("Geladeira");
        btnGeladeira.addActionListener(this::btnGeladeiraActionPerformed);

        btnBd.setText("Banco de Dados");
        btnBd.addActionListener(this::btnBdActionPerformed);

        jlChoose.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jlChoose.setForeground(new java.awt.Color(255, 255, 255));
        jlChoose.setText("Consultar itens em:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jlChoose, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnArmario)
                    .addComponent(btnGeladeira)
                    .addComponent(btnBd))
                .addContainerGap(156, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnArmario, btnBd, btnGeladeira});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jlChoose, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(btnArmario)
                .addGap(43, 43, 43)
                .addComponent(btnGeladeira)
                .addGap(43, 43, 43)
                .addComponent(btnBd)
                .addGap(53, 53, 53))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnArmarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArmarioActionPerformed
        new frmCategorizado(Categoria.ARMARIO).setVisible(true);  
    }//GEN-LAST:event_btnArmarioActionPerformed

    private void btnGeladeiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeladeiraActionPerformed
        new frmCategorizado(Categoria.GELADEIRA).setVisible(true);
    }//GEN-LAST:event_btnGeladeiraActionPerformed

    private void btnBdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBdActionPerformed
        new frmTodosItens().setVisible(true);
    }//GEN-LAST:event_btnBdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmLobby().setVisible(true));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArmario;
    private javax.swing.JButton btnBd;
    private javax.swing.JButton btnGeladeira;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlChoose;
    // End of variables declaration//GEN-END:variables
}
